//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hzconsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://remoteservice.mall.mk.com/", ConfigurationName="ServiceReference1.MallRemoteServcie")]
    public interface MallRemoteServcie {
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeGoodspriceResponse exchangeGoodsprice(hzconsole.ServiceReference1.exchangeGoodsprice request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodspriceResponse> exchangeGoodspriceAsync(hzconsole.ServiceReference1.exchangeGoodsprice request);
        
        // CODEGEN: 命名空间  的元素名称 orderguid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.showOrderResponse showOrder(hzconsole.ServiceReference1.showOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderResponse> showOrderAsync(hzconsole.ServiceReference1.showOrder request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.showOrderstatusResponse showOrderstatus(hzconsole.ServiceReference1.showOrderstatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderstatusResponse> showOrderstatusAsync(hzconsole.ServiceReference1.showOrderstatus request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeGoodsImgResponse exchangeGoodsImg(hzconsole.ServiceReference1.exchangeGoodsImg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsImgResponse> exchangeGoodsImgAsync(hzconsole.ServiceReference1.exchangeGoodsImg request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeOrderResponse exchangeOrder(hzconsole.ServiceReference1.exchangeOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrderResponse> exchangeOrderAsync(hzconsole.ServiceReference1.exchangeOrder request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.orderTimeResponse orderTime(hzconsole.ServiceReference1.orderTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderTimeResponse> orderTimeAsync(hzconsole.ServiceReference1.orderTime request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeGoodsURLResponse exchangeGoodsURL(hzconsole.ServiceReference1.exchangeGoodsURL request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsURLResponse> exchangeGoodsURLAsync(hzconsole.ServiceReference1.exchangeGoodsURL request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.goodsOnsaleResponse goodsOnsale(hzconsole.ServiceReference1.goodsOnsale request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.goodsOnsaleResponse> goodsOnsaleAsync(hzconsole.ServiceReference1.goodsOnsale request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeGoodsResponse exchangeGoods(hzconsole.ServiceReference1.exchangeGoods request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsResponse> exchangeGoodsAsync(hzconsole.ServiceReference1.exchangeGoods request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.exchangeOrgResponse exchangeOrg(hzconsole.ServiceReference1.exchangeOrg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrgResponse> exchangeOrgAsync(hzconsole.ServiceReference1.exchangeOrg request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference1.orderstatusResponse orderstatus(hzconsole.ServiceReference1.orderstatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderstatusResponse> orderstatusAsync(hzconsole.ServiceReference1.orderstatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsprice {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsprice", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodspriceBody Body;
        
        public exchangeGoodsprice() {
        }
        
        public exchangeGoodsprice(hzconsole.ServiceReference1.exchangeGoodspriceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodspriceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMGoodsprice;
        
        public exchangeGoodspriceBody() {
        }
        
        public exchangeGoodspriceBody(string sTicket, string sMGoodsprice) {
            this.sTicket = sTicket;
            this.sMGoodsprice = sMGoodsprice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodspriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodspriceResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodspriceResponseBody Body;
        
        public exchangeGoodspriceResponse() {
        }
        
        public exchangeGoodspriceResponse(hzconsole.ServiceReference1.exchangeGoodspriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodspriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeGoodspriceResponseBody() {
        }
        
        public exchangeGoodspriceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class showOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="showOrder", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.showOrderBody Body;
        
        public showOrder() {
        }
        
        public showOrder(hzconsole.ServiceReference1.showOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class showOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderguid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sTicket;
        
        public showOrderBody() {
        }
        
        public showOrderBody(string orderguid, string sTicket) {
            this.orderguid = orderguid;
            this.sTicket = sTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class showOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="showOrderResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.showOrderResponseBody Body;
        
        public showOrderResponse() {
        }
        
        public showOrderResponse(hzconsole.ServiceReference1.showOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class showOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public showOrderResponseBody() {
        }
        
        public showOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class showOrderstatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="showOrderstatus", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.showOrderstatusBody Body;
        
        public showOrderstatus() {
        }
        
        public showOrderstatus(hzconsole.ServiceReference1.showOrderstatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class showOrderstatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMOrderDetail;
        
        public showOrderstatusBody() {
        }
        
        public showOrderstatusBody(string sTicket, string sMOrderDetail) {
            this.sTicket = sTicket;
            this.sMOrderDetail = sMOrderDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class showOrderstatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="showOrderstatusResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.showOrderstatusResponseBody Body;
        
        public showOrderstatusResponse() {
        }
        
        public showOrderstatusResponse(hzconsole.ServiceReference1.showOrderstatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class showOrderstatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public showOrderstatusResponseBody() {
        }
        
        public showOrderstatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsImg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsImg", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsImgBody Body;
        
        public exchangeGoodsImg() {
        }
        
        public exchangeGoodsImg(hzconsole.ServiceReference1.exchangeGoodsImgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsImgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public exchangeGoodsImgBody() {
        }
        
        public exchangeGoodsImgBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsImgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsImgResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsImgResponseBody Body;
        
        public exchangeGoodsImgResponse() {
        }
        
        public exchangeGoodsImgResponse(hzconsole.ServiceReference1.exchangeGoodsImgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsImgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeGoodsImgResponseBody() {
        }
        
        public exchangeGoodsImgResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeOrder", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeOrderBody Body;
        
        public exchangeOrder() {
        }
        
        public exchangeOrder(hzconsole.ServiceReference1.exchangeOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        public exchangeOrderBody() {
        }
        
        public exchangeOrderBody(string sTicket) {
            this.sTicket = sTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeOrderResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeOrderResponseBody Body;
        
        public exchangeOrderResponse() {
        }
        
        public exchangeOrderResponse(hzconsole.ServiceReference1.exchangeOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeOrderResponseBody() {
        }
        
        public exchangeOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderTime", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.orderTimeBody Body;
        
        public orderTime() {
        }
        
        public orderTime(hzconsole.ServiceReference1.orderTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public orderTimeBody() {
        }
        
        public orderTimeBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderTimeResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.orderTimeResponseBody Body;
        
        public orderTimeResponse() {
        }
        
        public orderTimeResponse(hzconsole.ServiceReference1.orderTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public orderTimeResponseBody() {
        }
        
        public orderTimeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsURL {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsURL", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsURLBody Body;
        
        public exchangeGoodsURL() {
        }
        
        public exchangeGoodsURL(hzconsole.ServiceReference1.exchangeGoodsURLBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsURLBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public exchangeGoodsURLBody() {
        }
        
        public exchangeGoodsURLBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsURLResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsURLResponseBody Body;
        
        public exchangeGoodsURLResponse() {
        }
        
        public exchangeGoodsURLResponse(hzconsole.ServiceReference1.exchangeGoodsURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeGoodsURLResponseBody() {
        }
        
        public exchangeGoodsURLResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class goodsOnsale {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="goodsOnsale", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.goodsOnsaleBody Body;
        
        public goodsOnsale() {
        }
        
        public goodsOnsale(hzconsole.ServiceReference1.goodsOnsaleBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class goodsOnsaleBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sGoodsOnsale;
        
        public goodsOnsaleBody() {
        }
        
        public goodsOnsaleBody(string sTicket, string sGoodsOnsale) {
            this.sTicket = sTicket;
            this.sGoodsOnsale = sGoodsOnsale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class goodsOnsaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="goodsOnsaleResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.goodsOnsaleResponseBody Body;
        
        public goodsOnsaleResponse() {
        }
        
        public goodsOnsaleResponse(hzconsole.ServiceReference1.goodsOnsaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class goodsOnsaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public goodsOnsaleResponseBody() {
        }
        
        public goodsOnsaleResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoods {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoods", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsBody Body;
        
        public exchangeGoods() {
        }
        
        public exchangeGoods(hzconsole.ServiceReference1.exchangeGoodsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMGoods;
        
        public exchangeGoodsBody() {
        }
        
        public exchangeGoodsBody(string sTicket, string sMGoods) {
            this.sTicket = sTicket;
            this.sMGoods = sMGoods;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeGoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeGoodsResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeGoodsResponseBody Body;
        
        public exchangeGoodsResponse() {
        }
        
        public exchangeGoodsResponse(hzconsole.ServiceReference1.exchangeGoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeGoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeGoodsResponseBody() {
        }
        
        public exchangeGoodsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeOrg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeOrg", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeOrgBody Body;
        
        public exchangeOrg() {
        }
        
        public exchangeOrg(hzconsole.ServiceReference1.exchangeOrgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeOrgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        public exchangeOrgBody() {
        }
        
        public exchangeOrgBody(string sTicket) {
            this.sTicket = sTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeOrgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeOrgResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.exchangeOrgResponseBody Body;
        
        public exchangeOrgResponse() {
        }
        
        public exchangeOrgResponse(hzconsole.ServiceReference1.exchangeOrgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class exchangeOrgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public exchangeOrgResponseBody() {
        }
        
        public exchangeOrgResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderstatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderstatus", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.orderstatusBody Body;
        
        public orderstatus() {
        }
        
        public orderstatus(hzconsole.ServiceReference1.orderstatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderstatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMOrderDetail;
        
        public orderstatusBody() {
        }
        
        public orderstatusBody(string sTicket, string sMOrderDetail) {
            this.sTicket = sTicket;
            this.sMOrderDetail = sMOrderDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderstatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderstatusResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference1.orderstatusResponseBody Body;
        
        public orderstatusResponse() {
        }
        
        public orderstatusResponse(hzconsole.ServiceReference1.orderstatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderstatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public orderstatusResponseBody() {
        }
        
        public orderstatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MallRemoteServcieChannel : hzconsole.ServiceReference1.MallRemoteServcie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MallRemoteServcieClient : System.ServiceModel.ClientBase<hzconsole.ServiceReference1.MallRemoteServcie>, hzconsole.ServiceReference1.MallRemoteServcie {
        
        public MallRemoteServcieClient() {
        }
        
        public MallRemoteServcieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MallRemoteServcieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MallRemoteServcieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MallRemoteServcieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeGoodspriceResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsprice(hzconsole.ServiceReference1.exchangeGoodsprice request) {
            return base.Channel.exchangeGoodsprice(request);
        }
        
        public string exchangeGoodsprice(string sTicket, string sMGoodsprice) {
            hzconsole.ServiceReference1.exchangeGoodsprice inValue = new hzconsole.ServiceReference1.exchangeGoodsprice();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodspriceBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMGoodsprice = sMGoodsprice;
            hzconsole.ServiceReference1.exchangeGoodspriceResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsprice(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodspriceResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodspriceAsync(hzconsole.ServiceReference1.exchangeGoodsprice request) {
            return base.Channel.exchangeGoodspriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodspriceResponse> exchangeGoodspriceAsync(string sTicket, string sMGoodsprice) {
            hzconsole.ServiceReference1.exchangeGoodsprice inValue = new hzconsole.ServiceReference1.exchangeGoodsprice();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodspriceBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMGoodsprice = sMGoodsprice;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodspriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.showOrderResponse hzconsole.ServiceReference1.MallRemoteServcie.showOrder(hzconsole.ServiceReference1.showOrder request) {
            return base.Channel.showOrder(request);
        }
        
        public string showOrder(string orderguid, string sTicket) {
            hzconsole.ServiceReference1.showOrder inValue = new hzconsole.ServiceReference1.showOrder();
            inValue.Body = new hzconsole.ServiceReference1.showOrderBody();
            inValue.Body.orderguid = orderguid;
            inValue.Body.sTicket = sTicket;
            hzconsole.ServiceReference1.showOrderResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).showOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderResponse> hzconsole.ServiceReference1.MallRemoteServcie.showOrderAsync(hzconsole.ServiceReference1.showOrder request) {
            return base.Channel.showOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderResponse> showOrderAsync(string orderguid, string sTicket) {
            hzconsole.ServiceReference1.showOrder inValue = new hzconsole.ServiceReference1.showOrder();
            inValue.Body = new hzconsole.ServiceReference1.showOrderBody();
            inValue.Body.orderguid = orderguid;
            inValue.Body.sTicket = sTicket;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).showOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.showOrderstatusResponse hzconsole.ServiceReference1.MallRemoteServcie.showOrderstatus(hzconsole.ServiceReference1.showOrderstatus request) {
            return base.Channel.showOrderstatus(request);
        }
        
        public string showOrderstatus(string sTicket, string sMOrderDetail) {
            hzconsole.ServiceReference1.showOrderstatus inValue = new hzconsole.ServiceReference1.showOrderstatus();
            inValue.Body = new hzconsole.ServiceReference1.showOrderstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMOrderDetail = sMOrderDetail;
            hzconsole.ServiceReference1.showOrderstatusResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).showOrderstatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderstatusResponse> hzconsole.ServiceReference1.MallRemoteServcie.showOrderstatusAsync(hzconsole.ServiceReference1.showOrderstatus request) {
            return base.Channel.showOrderstatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.showOrderstatusResponse> showOrderstatusAsync(string sTicket, string sMOrderDetail) {
            hzconsole.ServiceReference1.showOrderstatus inValue = new hzconsole.ServiceReference1.showOrderstatus();
            inValue.Body = new hzconsole.ServiceReference1.showOrderstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMOrderDetail = sMOrderDetail;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).showOrderstatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeGoodsImgResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsImg(hzconsole.ServiceReference1.exchangeGoodsImg request) {
            return base.Channel.exchangeGoodsImg(request);
        }
        
        public string exchangeGoodsImg(string arg0, string arg1) {
            hzconsole.ServiceReference1.exchangeGoodsImg inValue = new hzconsole.ServiceReference1.exchangeGoodsImg();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsImgBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            hzconsole.ServiceReference1.exchangeGoodsImgResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsImg(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsImgResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsImgAsync(hzconsole.ServiceReference1.exchangeGoodsImg request) {
            return base.Channel.exchangeGoodsImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsImgResponse> exchangeGoodsImgAsync(string arg0, string arg1) {
            hzconsole.ServiceReference1.exchangeGoodsImg inValue = new hzconsole.ServiceReference1.exchangeGoodsImg();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsImgBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeOrderResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeOrder(hzconsole.ServiceReference1.exchangeOrder request) {
            return base.Channel.exchangeOrder(request);
        }
        
        public string exchangeOrder(string sTicket) {
            hzconsole.ServiceReference1.exchangeOrder inValue = new hzconsole.ServiceReference1.exchangeOrder();
            inValue.Body = new hzconsole.ServiceReference1.exchangeOrderBody();
            inValue.Body.sTicket = sTicket;
            hzconsole.ServiceReference1.exchangeOrderResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrderResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeOrderAsync(hzconsole.ServiceReference1.exchangeOrder request) {
            return base.Channel.exchangeOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrderResponse> exchangeOrderAsync(string sTicket) {
            hzconsole.ServiceReference1.exchangeOrder inValue = new hzconsole.ServiceReference1.exchangeOrder();
            inValue.Body = new hzconsole.ServiceReference1.exchangeOrderBody();
            inValue.Body.sTicket = sTicket;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.orderTimeResponse hzconsole.ServiceReference1.MallRemoteServcie.orderTime(hzconsole.ServiceReference1.orderTime request) {
            return base.Channel.orderTime(request);
        }
        
        public string orderTime(string arg0) {
            hzconsole.ServiceReference1.orderTime inValue = new hzconsole.ServiceReference1.orderTime();
            inValue.Body = new hzconsole.ServiceReference1.orderTimeBody();
            inValue.Body.arg0 = arg0;
            hzconsole.ServiceReference1.orderTimeResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).orderTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderTimeResponse> hzconsole.ServiceReference1.MallRemoteServcie.orderTimeAsync(hzconsole.ServiceReference1.orderTime request) {
            return base.Channel.orderTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderTimeResponse> orderTimeAsync(string arg0) {
            hzconsole.ServiceReference1.orderTime inValue = new hzconsole.ServiceReference1.orderTime();
            inValue.Body = new hzconsole.ServiceReference1.orderTimeBody();
            inValue.Body.arg0 = arg0;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).orderTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeGoodsURLResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsURL(hzconsole.ServiceReference1.exchangeGoodsURL request) {
            return base.Channel.exchangeGoodsURL(request);
        }
        
        public string exchangeGoodsURL(string arg0, string arg1) {
            hzconsole.ServiceReference1.exchangeGoodsURL inValue = new hzconsole.ServiceReference1.exchangeGoodsURL();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsURLBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            hzconsole.ServiceReference1.exchangeGoodsURLResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsURL(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsURLResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsURLAsync(hzconsole.ServiceReference1.exchangeGoodsURL request) {
            return base.Channel.exchangeGoodsURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsURLResponse> exchangeGoodsURLAsync(string arg0, string arg1) {
            hzconsole.ServiceReference1.exchangeGoodsURL inValue = new hzconsole.ServiceReference1.exchangeGoodsURL();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsURLBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.goodsOnsaleResponse hzconsole.ServiceReference1.MallRemoteServcie.goodsOnsale(hzconsole.ServiceReference1.goodsOnsale request) {
            return base.Channel.goodsOnsale(request);
        }
        
        public string goodsOnsale(string sTicket, string sGoodsOnsale) {
            hzconsole.ServiceReference1.goodsOnsale inValue = new hzconsole.ServiceReference1.goodsOnsale();
            inValue.Body = new hzconsole.ServiceReference1.goodsOnsaleBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sGoodsOnsale = sGoodsOnsale;
            hzconsole.ServiceReference1.goodsOnsaleResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).goodsOnsale(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.goodsOnsaleResponse> hzconsole.ServiceReference1.MallRemoteServcie.goodsOnsaleAsync(hzconsole.ServiceReference1.goodsOnsale request) {
            return base.Channel.goodsOnsaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.goodsOnsaleResponse> goodsOnsaleAsync(string sTicket, string sGoodsOnsale) {
            hzconsole.ServiceReference1.goodsOnsale inValue = new hzconsole.ServiceReference1.goodsOnsale();
            inValue.Body = new hzconsole.ServiceReference1.goodsOnsaleBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sGoodsOnsale = sGoodsOnsale;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).goodsOnsaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeGoodsResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoods(hzconsole.ServiceReference1.exchangeGoods request) {
            return base.Channel.exchangeGoods(request);
        }
        
        public string exchangeGoods(string sTicket, string sMGoods) {
            hzconsole.ServiceReference1.exchangeGoods inValue = new hzconsole.ServiceReference1.exchangeGoods();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMGoods = sMGoods;
            hzconsole.ServiceReference1.exchangeGoodsResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoods(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeGoodsAsync(hzconsole.ServiceReference1.exchangeGoods request) {
            return base.Channel.exchangeGoodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeGoodsResponse> exchangeGoodsAsync(string sTicket, string sMGoods) {
            hzconsole.ServiceReference1.exchangeGoods inValue = new hzconsole.ServiceReference1.exchangeGoods();
            inValue.Body = new hzconsole.ServiceReference1.exchangeGoodsBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMGoods = sMGoods;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeGoodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.exchangeOrgResponse hzconsole.ServiceReference1.MallRemoteServcie.exchangeOrg(hzconsole.ServiceReference1.exchangeOrg request) {
            return base.Channel.exchangeOrg(request);
        }
        
        public string exchangeOrg(string sTicket) {
            hzconsole.ServiceReference1.exchangeOrg inValue = new hzconsole.ServiceReference1.exchangeOrg();
            inValue.Body = new hzconsole.ServiceReference1.exchangeOrgBody();
            inValue.Body.sTicket = sTicket;
            hzconsole.ServiceReference1.exchangeOrgResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeOrg(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrgResponse> hzconsole.ServiceReference1.MallRemoteServcie.exchangeOrgAsync(hzconsole.ServiceReference1.exchangeOrg request) {
            return base.Channel.exchangeOrgAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.exchangeOrgResponse> exchangeOrgAsync(string sTicket) {
            hzconsole.ServiceReference1.exchangeOrg inValue = new hzconsole.ServiceReference1.exchangeOrg();
            inValue.Body = new hzconsole.ServiceReference1.exchangeOrgBody();
            inValue.Body.sTicket = sTicket;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).exchangeOrgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference1.orderstatusResponse hzconsole.ServiceReference1.MallRemoteServcie.orderstatus(hzconsole.ServiceReference1.orderstatus request) {
            return base.Channel.orderstatus(request);
        }
        
        public string orderstatus(string sTicket, string sMOrderDetail) {
            hzconsole.ServiceReference1.orderstatus inValue = new hzconsole.ServiceReference1.orderstatus();
            inValue.Body = new hzconsole.ServiceReference1.orderstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMOrderDetail = sMOrderDetail;
            hzconsole.ServiceReference1.orderstatusResponse retVal = ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).orderstatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderstatusResponse> hzconsole.ServiceReference1.MallRemoteServcie.orderstatusAsync(hzconsole.ServiceReference1.orderstatus request) {
            return base.Channel.orderstatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference1.orderstatusResponse> orderstatusAsync(string sTicket, string sMOrderDetail) {
            hzconsole.ServiceReference1.orderstatus inValue = new hzconsole.ServiceReference1.orderstatus();
            inValue.Body = new hzconsole.ServiceReference1.orderstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMOrderDetail = sMOrderDetail;
            return ((hzconsole.ServiceReference1.MallRemoteServcie)(this)).orderstatusAsync(inValue);
        }
    }
}
