//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hzconsole.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://remoteservice.mall.mk.com/", ConfigurationName="ServiceReference2.MContractRemoteService")]
    public interface MContractRemoteService {
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference2.contractResponse contract(hzconsole.ServiceReference2.contract request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractResponse> contractAsync(hzconsole.ServiceReference2.contract request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference2.draftResponse draft(hzconsole.ServiceReference2.draft request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.draftResponse> draftAsync(hzconsole.ServiceReference2.draft request);
        
        // CODEGEN: 命名空间  的元素名称 sTicket 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        hzconsole.ServiceReference2.contractstatusResponse contractstatus(hzconsole.ServiceReference2.contractstatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractstatusResponse> contractstatusAsync(hzconsole.ServiceReference2.contractstatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contract {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contract", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.contractBody Body;
        
        public contract() {
        }
        
        public contract(hzconsole.ServiceReference2.contractBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class contractBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMcontract;
        
        public contractBody() {
        }
        
        public contractBody(string sTicket, string sMcontract) {
            this.sTicket = sTicket;
            this.sMcontract = sMcontract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contractResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.contractResponseBody Body;
        
        public contractResponse() {
        }
        
        public contractResponse(hzconsole.ServiceReference2.contractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class contractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public contractResponseBody() {
        }
        
        public contractResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class draft {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="draft", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.draftBody Body;
        
        public draft() {
        }
        
        public draft(hzconsole.ServiceReference2.draftBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class draftBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMcontract;
        
        public draftBody() {
        }
        
        public draftBody(string sTicket, string sMcontract) {
            this.sTicket = sTicket;
            this.sMcontract = sMcontract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class draftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="draftResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.draftResponseBody Body;
        
        public draftResponse() {
        }
        
        public draftResponse(hzconsole.ServiceReference2.draftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class draftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public draftResponseBody() {
        }
        
        public draftResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contractstatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contractstatus", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.contractstatusBody Body;
        
        public contractstatus() {
        }
        
        public contractstatus(hzconsole.ServiceReference2.contractstatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class contractstatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sMcontract;
        
        public contractstatusBody() {
        }
        
        public contractstatusBody(string sTicket, string sMcontract) {
            this.sTicket = sTicket;
            this.sMcontract = sMcontract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contractstatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contractstatusResponse", Namespace="http://remoteservice.mall.mk.com/", Order=0)]
        public hzconsole.ServiceReference2.contractstatusResponseBody Body;
        
        public contractstatusResponse() {
        }
        
        public contractstatusResponse(hzconsole.ServiceReference2.contractstatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class contractstatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public contractstatusResponseBody() {
        }
        
        public contractstatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MContractRemoteServiceChannel : hzconsole.ServiceReference2.MContractRemoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MContractRemoteServiceClient : System.ServiceModel.ClientBase<hzconsole.ServiceReference2.MContractRemoteService>, hzconsole.ServiceReference2.MContractRemoteService {
        
        public MContractRemoteServiceClient() {
        }
        
        public MContractRemoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MContractRemoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MContractRemoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MContractRemoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference2.contractResponse hzconsole.ServiceReference2.MContractRemoteService.contract(hzconsole.ServiceReference2.contract request) {
            return base.Channel.contract(request);
        }
        
        public string contract(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.contract inValue = new hzconsole.ServiceReference2.contract();
            inValue.Body = new hzconsole.ServiceReference2.contractBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            hzconsole.ServiceReference2.contractResponse retVal = ((hzconsole.ServiceReference2.MContractRemoteService)(this)).contract(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractResponse> hzconsole.ServiceReference2.MContractRemoteService.contractAsync(hzconsole.ServiceReference2.contract request) {
            return base.Channel.contractAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractResponse> contractAsync(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.contract inValue = new hzconsole.ServiceReference2.contract();
            inValue.Body = new hzconsole.ServiceReference2.contractBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            return ((hzconsole.ServiceReference2.MContractRemoteService)(this)).contractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference2.draftResponse hzconsole.ServiceReference2.MContractRemoteService.draft(hzconsole.ServiceReference2.draft request) {
            return base.Channel.draft(request);
        }
        
        public string draft(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.draft inValue = new hzconsole.ServiceReference2.draft();
            inValue.Body = new hzconsole.ServiceReference2.draftBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            hzconsole.ServiceReference2.draftResponse retVal = ((hzconsole.ServiceReference2.MContractRemoteService)(this)).draft(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.draftResponse> hzconsole.ServiceReference2.MContractRemoteService.draftAsync(hzconsole.ServiceReference2.draft request) {
            return base.Channel.draftAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference2.draftResponse> draftAsync(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.draft inValue = new hzconsole.ServiceReference2.draft();
            inValue.Body = new hzconsole.ServiceReference2.draftBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            return ((hzconsole.ServiceReference2.MContractRemoteService)(this)).draftAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hzconsole.ServiceReference2.contractstatusResponse hzconsole.ServiceReference2.MContractRemoteService.contractstatus(hzconsole.ServiceReference2.contractstatus request) {
            return base.Channel.contractstatus(request);
        }
        
        public string contractstatus(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.contractstatus inValue = new hzconsole.ServiceReference2.contractstatus();
            inValue.Body = new hzconsole.ServiceReference2.contractstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            hzconsole.ServiceReference2.contractstatusResponse retVal = ((hzconsole.ServiceReference2.MContractRemoteService)(this)).contractstatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractstatusResponse> hzconsole.ServiceReference2.MContractRemoteService.contractstatusAsync(hzconsole.ServiceReference2.contractstatus request) {
            return base.Channel.contractstatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<hzconsole.ServiceReference2.contractstatusResponse> contractstatusAsync(string sTicket, string sMcontract) {
            hzconsole.ServiceReference2.contractstatus inValue = new hzconsole.ServiceReference2.contractstatus();
            inValue.Body = new hzconsole.ServiceReference2.contractstatusBody();
            inValue.Body.sTicket = sTicket;
            inValue.Body.sMcontract = sMcontract;
            return ((hzconsole.ServiceReference2.MContractRemoteService)(this)).contractstatusAsync(inValue);
        }
    }
}
